# Generated by Django 5.0.3 on 2024-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in_time',
            new_name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
