# Generated by Django 5.0.3 on 2024-03-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_attendance_check_out_alter_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
