# Generated by Django 5.0.3 on 2024-03-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='tasks',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
