# Generated by Django 5.0.3 on 2024-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
