# Generated by Django 5.0.3 on 2024-04-04 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='tomorrow_tasks',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(default=False),
        ),
    ]
