# Generated by Django 5.0.3 on 2024-04-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_attendance_tomorrow_tasks_user_hobbies_user_hometown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='today_tasks_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='todays_tasks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='tomorrow_tasks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
