# Generated by Django 5.0.3 on 2024-03-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_attendance_tasks_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
