# Generated by Django 5.0.3 on 2024-03-21 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='tasks',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
