# Generated by Django 5.0.3 on 2024-04-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_attendance_today_tasks_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='today_tasks_completed',
            new_name='today_tasks_status',
        ),
    ]
