# Generated by Django 5.0.3 on 2024-03-23 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_attendance_check_out_alter_user_hire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hometown',
            field=models.CharField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
