# Generated by Django 5.0.3 on 2024-03-22 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_attendance_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
