# Generated by Django 5.0.3 on 2024-03-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_user_hobbies_user_hometown_user_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
