# Generated by Django 5.0.3 on 2024-03-22 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_attendance_check_out_alter_user_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 30, 28, 321801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 5, 30, 28, 321801, tzinfo=datetime.timezone.utc)),
        ),
    ]
