# Generated by Django 5.0.3 on 2024-04-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_attendance_today_tasks_status'),
        ('employee', '0014_alter_user_image'),
    ]

    operations = [
    ]
