# Generated by Django 5.0.3 on 2024-04-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
